config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root "projects#index" 

 resources :projects
 resources :projectlocations
 resources :projectusers

 resources :forumtopics do
 	resources :forumposts
 end

end

app/models/project.rb
class Project < ApplicationRecord

    has_many :projectrequirements
    has_many :projectlicenses
    has_many :projecttags
    has_many :projectusers
    has_many :forumtopics
    has_many :projectfiles
    has_many :deadlines
    has_one  :projectlocation

    belongs_to :projecttype
end

app/models/projecttype.rb
class Projecttype < ApplicationRecord

    has_many :projects
    has_many :projecttypelicenses
    has_many :projecttyperequirements
    has_many :projecttypetags

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :authenticate_user!
    before_action :find_project, only: [:show, :edit, :update, :destroy]

    def index

        @own_projects ||= []
        @employee_projects ||= []
        @neighbouring_projects ||= []

        current_user.projectusers.all.each do |projectuser|
            if projectuser.projectusertype.id == 1
                @own_projects << projectuser.project
            end

            if projectuser.projectusertype.id == 2
                @employee_projects << projectuser.project
            end

            if projectuser.projectusertype.id == 3
                @own_projects << projectuser.project
            end
        end
    end

    def show
        # make sure the user is authenticated
        # we will now check whether or not the project has the correct shit

        if @project.state == nil
            # this probably means this hasn't been instantiated #fixthis
            @project.state = 1
            @project.save
        end

        @counter = 0

        if @project.state == 1

            @project.projectrequirements.all.each do |require|
                if require.state == 1
                    @counter += 1
                end
            end

            if @counter == 0
                @project.state = 2
                @project.save
            end
        end

        if @project.state == 2
            @project.projecttags.all.each do |tag|
                if tag.state == 1
                    @counter += 1
                end
            end

            if @counter == 0
                @project.state = 3
                @project.save
            end
        end

        if @project.state == 3
            @project.projectlicenses.all.each do |license|
                if license.state == 1
                    @counter += 1
                end

                if license.state == 3
                    @counter = -1
                    break
                end
            end

            if @counter == 0
                @project.state = 4
                @project.save
            end
        end

        is_authenticated = false

        @project.projectusers.all.each do |projectuser|
            if projectuser.user_id == current_user.id
                is_authenticated = true
                break
            end
        end

        if is_authenticated
            @projectuser = Projectuser.new 
            @projectuser.project_id = @project.id 
            @projectuser.projectusertype_id = 2

            # this way we can add more data
            # make sure we find all the correct data here
        else
            redirect_to root_path
        end
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new( project_params )

        if @project.save
            # make sure we create a projectuser

            projectuser = Projectuser.new

            projectuser.user_id = current_user.id
            projectuser.project_id = @project.id
            projectuser.projectusertype_id = 1

            #already create the forum; just for fun
            forumtopic = Forumtopic.new
            forumtopic.name = "alleen voor eigenaren"
            forumtopic.rights = 1
            forumtopic.user_id = current_user.id
            forumtopic.save

            forumtopic = Forumtopic.new
            forumtopic.name = "Alles voor de development"
            forumtopic.rights = 2
            forumtopic.user_id = current_user.id
            forumtopic.save

            forumtopic = Forumtopic.new
            forumtopic.name = "Publiek forum"
            forumtopic.rights = 3
            forumtopic.user_id = current_user.id
            forumtopic.save

            projectuser.save

            redirect_to new_projectlocation_path( project_id: @project.id )
        else
            render 'new'
        end
    end

    def edit
        #check if this guy is an owner

        is_owner = false

        @project.projectuser.all.each do |projectuser|
            if projectuser.user_ud == current_user.id
                if projectuser.projectusertype_id == 1
                    is_owner = true
                end
                break
            end
        end

        unless is_owner
            redirect_to root_path
        end
    end

    def update
        is_owner = false

        @project.projectuser.all.each do |projectuser|
            if projectuser.user_ud == current_user.id
                if projectuser.projectusertype_id == 1
                    is_owner = true
                end
                break
            end
        end

        unless is_owner
            redirect_to root_path
        else

            if @project.update( project_params )
                redirect_to @project
            else
                render 'edit'
            end

        end
    end

    def destroy
        is_owner = false

        @project.projectuser.all.each do |projectuser|
            if projectuser.user_ud == current_user.id
                if projectuser.projectusertype_id == 1
                    is_owner = true
                end
                break
            end
        end

        if is_owner
            @project.destroy
            redirect_to root_path
        else
            redirect_to root_path
        end

    end

    private

    def find_project
    	@project = Project.find_by_id(params[:id])
    end

    def project_params
        params.require(:project).permit([:name, :projecttype_id])
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<main>
    <div class="container">
      <div class="row">
        <div class="col-md-2"></div>
          <div class="col-md-8 text-center">
            <div class="com-newproject">
              <div id="new_project_div" class="btn">
                <%= link_to "new project", new_project_path %>
              </div>
                <div class="line-seperator">
                </div>

              <div id="own_projects">
                  <div class="projects-field">
                      <h2>Mijn projecten</h2>
                      <% @own_projects.each do |project| %>
                      <!-- Als je hier iets wilt toevoegen zoals naam ofzo
                       <div id="new_project_div" class="btn">
                      <%= link_to "new project", new_project_path %>
                    </div>
                      gebruik <%=project.name%> -->
                          <div id="new_project_div" class="btn">
                            <%= link_to project.name, project %>
                          </div>
                        <% end %>
                  </div>
              </div>

                <div class="line-seperator">
                </div>

              <div id="employee_projects">
                  <div class="projects-field">
                      <h2>Projecten in mijn werkomgeving</h2>
                        <% @employee_projects.each do |project| %>
                        <!-- Als je hier iets wilt toevoegen zoals naam ofzo
                        gebruik <%=project.name%> -->
                      <div> <%=link_to project.name, project %> </div>
                        <% end %>
                  </div>
              </div>

                <div class="line-seperator">
                </div>

              <div id="neighbouring_projects">
                  <div class="projects-field">
                      <h2>Projecten in mijn buurt</h2>
                      <% @neighbouring_projects.each do |project| %>
                          <!-- Als je hier iets wilt toevoegen zoals naam ofzo
                              gebruik <%=project.name%> -->
                      <div> <%=link_to project.name, project %> </div>
                      <% end %>
                  </div>
            </div>
          </div>
          </div>
        </div>
      </div>
</main>

app/views/projects/new.html.erb
<main>
    <div class="page-wrapper">
        <div class="section-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-xs-1"></div>
                        <div class="col-md-8">
                   <div class="com-newproject">
                        <%= simple_form_for @project do |f| %>

                       <p> Project type </p>
                       <%= f.association :projecttype, label: false %>

                        <br>
                        <p> Project naam </p>

                         <%= f.input :name, label: false %>

                         <%= f.submit %>

                         <% end %>
                     </div>
                        </div>
                    <div class="col-md-2"></div>
                </div>
            </div>
        </div>
    </div>
</main>

app/views/projects/show.html.erb
<div class="section-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-md-2"></div>
				<div class="col-md-8">
					<h1><%= @project.name %></h1>
				</div>
				<div class="col-md-1"></div>
				<div class="col-md-1">
				</div>
		</div>

<hr>

<header>

	<% if @project.state == 1 %>
	    <div class="stepbar-wrapper">
	        <div class="stepbar">
	            <ul class="stepbar-layout">
	                <li><a href="#"><div class="step active">1</div></a></li>
	                <li><div class="bar last"></div><div></div></li>
	                <li><a href="#"><div class="step current">2</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="/projects/21"><div class="step">3</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="#"><div class="step">4</div></a></li>
	                <li><div class="bar"><div></div></div></li>
	                <li><a href="#"><div class="step">5</div></a></li>
	            </ul>
	        </div>
	    </div>
    <%end%>

    <%if @project.state == 2 %>
	    <div class="stepbar-wrapper">
	        <div class="stepbar">
	            <ul class="stepbar-layout">
	                <li><a href="#"><div class="step active">1</div></a></li>
	                <li><div class="bar active"></div><div></div></li>
	                <li><a href="#"><div class="step active">2</div></a></li>
	                <li><div class="bar last"></div><div></div></li>
	                <li><a href="#"><div class="step current">3</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="#"><div class="step">4</div></a></li>
	                <li><div class="bar"><div></div></div></li>
	                <li><a href="#"><div class="step">5</div></a></li>
	            </ul>
	        </div>
	    </div>
   <%end%>
   <%if @project.state == 3 %>
	    <div class="stepbar-wrapper">
	        <div class="stepbar">
	            <ul class="stepbar-layout">
	                <li><a href="#"><div class="step current">1</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="/projects/18"><div class="step ">2</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="#"><div class="step ">3</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="#"><div class="step">4</div></a></li>
	                <li><div class="bar"><div></div></div></li>
	                <li><a href="#"><div class="step">5</div></a></li>
	            </ul>
	        </div>
	    </div>
   <%end%>
   <%if @project.state == 4 %>
	    <div class="stepbar-wrapper">
	        <div class="stepbar">
	            <ul class="stepbar-layout">
	                <li><a href="#"><div class="step active">1</div></a></li>
	                <li><div class="bar active"></div><div></div></li>
	                <li><a href="#"><div class="step active">2</div></a></li>
	                <li><div class="bar last"></div><div></div></li>
	                <li><a href="#"><div class="step current">3</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="/projects/11"><div class="step">4</div></a></li>
	                <li><div class="bar"><div></div></div></li>
	                <li><a href="#"><div class="step">5</div></a></li>
	            </ul>
	        </div>
	    </div>
   <%end%>
   <%if @project.state == 5 %>
	    <div class="stepbar-wrapper">
	        <div class="stepbar">
	            <ul class="stepbar-layout">
	                <li><a href="#"><div class="step active">1</div></a></li>
	                <li><div class="bar active"></div><div></div></li>
	                <li><a href="#"><div class="step active">2</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="#"><div class="step active">3</div></a></li>
	                <li><div class="bar"></div><div></div></li>
	                <li><a href="#"><div class="step active">4</div></a></li>
	                <li><div class="bar"><div></div></div></li>
	                <li><a href="#"><div class="step active">5</div></a></li>
	            </ul>
	        </div>
	    </div>
   <%end%>
</header>


	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<div class="com-newproject">

<% if @project.state == 1 %>
	<div id='requirements_required'>
		<center>
			<table>
				<% @project.projectrequirements.all.each do |requirement| %>
					<tr>
						<% if requirement.state == 1 %>
							<td><h3><i class="fa fa-clock-o"></i></span></h3></td>
						<% end %>
						<td><h3> <%= requirement.name %> </h3></td>
					</tr>
				<% end %>
			</table>
		</center>
	</div>

	<style>

		h3 {
			text-align: left;
			font-size: 27px;
		}
	</style>
<% end %>

<% if @project.state == 2 %>

	<div id="people_required">
		<center>
			<h2> We still need these people! </h2>

			<% @project.projecttags.all.each do |tag| %>

				<% if tag.state == 1 %>
					<h3> <%= tag.tag.name %> </h3>
				<% end %>
			<% end %>

			<p> let's add some people </p>
			<%= simple_form_for @projectuser do |f| %>

				<%= f.input :project_id, :as => :hidden %>
				<%= f.input :projectusertype_id, :as => :hidden %>
				<%= f.input :user_id, :as => :hidden %>

				<input type='text' id='email_input' />
				<a id="check_email">CHECK</a>

				<%= f.submit %>

			<% end %>

		</center>
	</div>

<% end %>

<% if @project.state == 3 %>
	<div id='licenses_required'>
		<center>
			<h2> Licenses required </h2>

			<% @project.projectlicenses.all.each do |license| %>
				<% if license.state == 1 %>
					<h3> <%= license.license.name %> </h3>
				<% end %>
			<% end %>
		</center>
	</div>

<% end %>


<% if @project.state == 4 %>
	
<% end %>


<% if @project.state == 5 %>
	Komen wij toch niet
<% end %>
</div>
</div>
<div class="col-md-2"></div>
</div>

<script type='text/javascript'>


	// make sure that we can load users

	$("#check_email").click(function() {
		var email_input = $("#email_input").val();
		$.ajax({
		  url: "http://localhost:3000/projectusers/",
		  type: "get", //send it through get method
		  data: {
		  	email: email_input
		  },
		  success: function(response) {
		    //Do Something
		    if( response.exists ) {
		    	$("#email_input").css("background", "green");
		    	$("#projectuser_user_id").val(response.user_id);
		    }
		  },
		  error: function(xhr) {
		    console.log( xhr );
		  }
		});
	});


</script>
</div>
</div>
</div>